-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 21:40:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema archive
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema archive
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `archive` DEFAULT CHARACTER SET utf8 ;
USE `archive` ;

-- -----------------------------------------------------
-- Table `archive`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archive`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Surname` VARCHAR(30) NOT NULL,
  `cName` VARCHAR(30) NOT NULL,
  `Middlename` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archive`.`Archive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archive`.`Archive` (
  `idArchive` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Filename` VARCHAR(45) NOT NULL,
  `idClient` INT NOT NULL,
  PRIMARY KEY (`idArchive`),
  INDEX `Client_idx` (`idClient` ASC) VISIBLE,
  CONSTRAINT `Client`
    FOREIGN KEY (`idClient`)
    REFERENCES `archive`.`Client` (`idClient`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
