-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 17:51:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capitaldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema capitaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capitaldb` DEFAULT CHARACTER SET utf8 ;
USE `capitaldb` ;

-- -----------------------------------------------------
-- Table `capitaldb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitaldb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `vip` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitaldb`.`worker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitaldb`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `salary` INT NULL,
  `position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitaldb`.`investplan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitaldb`.`investplan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(20) NOT NULL,
  `min` INT NOT NULL,
  `profit` INT NOT NULL,
  `risk` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitaldb`.`relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitaldb`.`relation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idworker` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `iduser_idx` (`iduser` ASC) VISIBLE,
  INDEX `idworker_idx` (`idworker` ASC) VISIBLE,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `capitaldb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idworker`
    FOREIGN KEY (`idworker`)
    REFERENCES `capitaldb`.`worker` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capitaldb`.`invest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `capitaldb`.`invest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idinvestplan` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `iduser_idx` (`iduser` ASC) VISIBLE,
  INDEX `idinvest_idx` (`idinvestplan` ASC) VISIBLE,
  CONSTRAINT `iduser`
    FOREIGN KEY (`iduser`)
    REFERENCES `capitaldb`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idinvest`
    FOREIGN KEY (`idinvestplan`)
    REFERENCES `capitaldb`.`investplan` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `capitaldb`;

DELIMITER $$
USE `capitaldb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `capitaldb`.`user_AFTER_INSERT` AFTER INSERT ON `user` FOR EACH ROW
BEGIN
	Insert into relation(iduser) VALUES(NEW.id);
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
